language: node_js
services:
  - "docker"

before_install:
    - "nvm install lts/* --reinstall-packages-from=node"
    - "npm i -g npm@6.8.0"
script:
    - "npx gulp lint"
    - "docker build -t impeach ."

notifications:
    email: false
